name: Node.js CI

on:
  push:
    branches: [ main, temp ]
  pull_request:
    branches: [ main, temp ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

  eslint-security-test:
    runs-on: ubuntu-latest
    needs: test  # This makes ESLint wait for tests to complete successfully
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    # Install dependencies
    - name: Install dependencies
      run: npm ci
      
    # Install ESLint and security plugin specifically
    - name: Install ESLint and security plugin
      run: |
        npm install eslint eslint-plugin-security globals --save-dev
        npx eslint --version
        
    # Debug: Check ESLint installation
    - name: Debug ESLint installation
      run: |
        which eslint || echo "eslint not in PATH"
        ls -la node_modules/.bin/eslint || echo "eslint binary not found"
        chmod +x node_modules/.bin/eslint || echo "chmod failed"
      
    # Run ESLint on the tests folder
    - name: Run ESLint on tests
      run: npx eslint ./tests/test.cjs
      continue-on-error: true  # This allows the workflow to continue even if ESLint finds issues
      
    # Run ESLint on entire project (optional)
    - name: Run ESLint on entire project
      run: npx eslint .
      continue-on-error: true
      
    # Generate ESLint report (optional)
    - name: Generate ESLint report
      run: npx eslint . --format json --output-file eslint-report.json
      continue-on-error: true
      
    # Upload ESLint report as artifact (optional)
    - name: Upload ESLint report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eslint-report
        path: eslint-report.json